# Generated by Django 5.2.17 on 2026-10-03 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mieszkaniec', 'Mieszkaniec / NGO'), ('jst', 'JST (samorząd)'), ('ekspert', 'Ekspert branżowy'), ('rops', 'Pracownik ROPS'), ('admin', 'Administrator')], default='mieszkaniec', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('powiat', models.CharField(blank=True, max_length=60)),
                ('is_expert', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profile',
            },
        ),
    ]
