# Generated by Django 5.2.17 on 2026-10-03 15:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.SlugField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('problem', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('target', models.TextField(blank=True)),
                ('beneficiaries', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('pdf', models.URLField(blank=True, null=True)),
                ('zip', models.URLField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=80, null=True)),
                ('url', models.URLField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=48, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innovations', to='catalog.category')),
            ],
            options={
                'verbose_name': 'innowacja',
                'verbose_name_plural': 'innowacje',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powiat', models.CharField(max_length=60)),
                ('org', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('demo', models.BooleanField(default=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='catalog.innovation')),
            ],
            options={
                'verbose_name': 'wdrożenie',
                'verbose_name_plural': 'wdrożenia',
                'ordering': ['powiat', 'org'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=400)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'dokument',
                'verbose_name_plural': 'dokumenty',
                'ordering': ['section', 'title'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='library_search_gin')],
            },
        ),
        migrations.AddIndex(
            model_name='innovation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_search_gin'),
        ),
    ]
