# Generated by Django 5.2.17 on 2026-10-03 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('powiat', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('unknown', models.JSONField(blank=True, default=list)),
                ('top_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result_count', models.PositiveSmallIntegerField(default=0)),
                ('is_gap', models.BooleanField(default=False)),
                ('gap_reason', models.CharField(blank=True, max_length=40)),
                ('ai_source', models.CharField(blank=True, max_length=20)),
                ('results', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zapytanie',
                'verbose_name_plural': 'zapytania',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w trakcie', 'W trakcie'), ('zamknięte', 'Zamknięte')], default='nowe', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap', to='hub.thread')),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gap', to='matchmaking.searchquery')),
            ],
            options={
                'verbose_name': 'luka',
                'verbose_name_plural': 'luki',
                'ordering': ['-created_at'],
            },
        ),
    ]
