# Generated by Django 5.2.17 on 2026-10-03 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('threshold', models.FloatField(default=0.5)),
                ('related', models.BooleanField(blank=True, null=True)),
                ('noul', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('powod', models.CharField(blank=True, max_length=400)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('jev_model', models.CharField(blank=True, max_length=40)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relevance_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ocena powiązania',
                'verbose_name_plural': 'oceny powiązań',
                'ordering': ['-created_at'],
            },
        ),
    ]
