# Generated by Django 5.2.17 on 2026-10-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_relevancecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=240, unique=True)),
                ('label', models.CharField(max_length=240)),
                ('kind', models.CharField(choices=[('wątki', 'Rozpoznane wątki'), ('nowe pojęcia', 'Słowa spoza bazy ROPS'), ('opis', 'Sam opis problemu')], default='opis', max_length=20)),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('searches', models.PositiveIntegerField(default=0)),
                ('unmet_searches', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('powiats', models.JSONField(blank=True, default=dict)),
                ('samples', models.JSONField(blank=True, default=list)),
                ('clients', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'temat zapytań',
                'verbose_name_plural': 'tematy zapytań',
                'ordering': ['-unmet_searches', '-searches'],
            },
        ),
        migrations.AddField(
            model_name='searchquery',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='matchmaking.demandtopic'),
        ),
    ]
