# Generated by Django 5.2.17 on 2026-10-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_demandtopic_searchquery_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandtopic',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
