# Generated by Django 5.2.17 on 2026-10-03 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pomysł', 'Pomysł'), ('luka', 'Luka'), ('pytanie', 'Pytanie'), ('test', 'Testowanie'), ('partner', 'Szukam partnera'), ('ekspert', 'Pytanie do eksperta')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('author_name', models.CharField(default='Mieszkaniec (demo)', max_length=120)),
                ('author_role', models.CharField(choices=[('mieszkaniec', 'Mieszkaniec / NGO'), ('jst', 'JST (samorząd)'), ('ekspert', 'Ekspert branżowy'), ('rops', 'Pracownik ROPS'), ('admin', 'Administrator')], default='mieszkaniec', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('powiat', models.CharField(blank=True, db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w trakcie', 'W trakcie'), ('odpowiedziane', 'Odpowiedziane'), ('zamknięte', 'Zamknięte')], db_index=True, default='nowe', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('stage', models.CharField(blank=True, choices=[('zgłoszony', 'Zgłoszony'), ('walidowany', 'Walidowany'), ('w testach', 'W testach'), ('wdrożony', 'Wdrożony')], db_index=True, max_length=20)),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('unknown_terms', models.JSONField(blank=True, default=list)),
                ('top_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('innovation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='catalog.innovation')),
            ],
            options={
                'verbose_name': 'wątek',
                'verbose_name_plural': 'watki',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('zgloszenia', 'Zgłoszenia'), ('nabory', 'Nabory grantowe'), ('odpowiedzi', 'Odpowiedzi')], default='zgloszenia', max_length=24)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hub.thread')),
            ],
            options={
                'verbose_name': 'powiadomienie',
                'verbose_name_plural': 'powiadomienia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Mieszkaniec (demo)', max_length=120)),
                ('role', models.CharField(default='mieszkaniec', max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hub.thread')),
            ],
            options={
                'verbose_name': 'wiadomość',
                'verbose_name_plural': 'wiadomości',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fiszka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istota', models.TextField()),
                ('adresat', models.TextField()),
                ('etap', models.CharField(choices=[('pomysł', 'Pomysł'), ('prototyp', 'Prototyp'), ('testowanie', 'Testowanie'), ('gotowe do skalowania', 'Gotowe do skalowania')], default='pomysł', max_length=32)),
                ('obszar', models.CharField(blank=True, max_length=120)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiszka', to='hub.thread')),
            ],
            options={
                'verbose_name': 'fiszka',
                'verbose_name_plural': 'fiszki',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('client_id', models.CharField(blank=True, default='', max_length=64)),
                ('author_name', models.CharField(default='Tester (demo)', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.innovation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ocena',
                'verbose_name_plural': 'oceny',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('innovation', 'client_id'), name='hub_rating_unique_per_client')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('mam_to', 'Mam ten problem'), ('chce_testowac', 'Chcę testować'), ('moge_pomoc', 'Mogę pomóc')], max_length=24)),
                ('client_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='hub.thread')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'głos',
                'verbose_name_plural': 'głosy',
                'constraints': [models.UniqueConstraint(fields=('thread', 'value', 'client_id'), name='hub_vote_unique_per_client')],
            },
        ),
    ]
