# Generated by Django 5.2.17 on 2026-10-03 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_type', models.CharField(choices=[('gmina wiejska', 'gmina wiejska'), ('gmina miejska', 'gmina miejska'), ('CUS / OPS', 'CUS / OPS'), ('powiat (PCPR)', 'powiat (PCPR)'), ('NGO / fundacja', 'NGO / fundacja'), ('DPS / placówka', 'DPS / placówka')], max_length=40)),
                ('size_band', models.CharField(choices=[('do 5 tys.', 'do 5 tys.'), ('5–20 tys.', '5–20 tys.'), ('20–100 tys.', '20–100 tys.'), ('powyżej 100 tys.', 'powyżej 100 tys.')], max_length=20)),
                ('budget', models.PositiveIntegerField(default=0, help_text='Budżet roczny na działanie, zł')),
                ('staff', models.PositiveSmallIntegerField(default=1, help_text='Ile osób może to prowadzić')),
                ('powiat', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil instytucji',
                'verbose_name_plural': 'profile instytucji',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('scale', models.CharField(blank=True, max_length=240)),
                ('staffing', models.CharField(blank=True, max_length=240)),
                ('cost_low', models.PositiveIntegerField(default=0)),
                ('cost_high', models.PositiveIntegerField(default=0)),
                ('affordable', models.BooleanField(default=True)),
                ('steps', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('adaptations', models.JSONField(default=list)),
                ('legal', models.JSONField(default=list)),
                ('source', models.CharField(default='regula', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='catalog.innovation')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='middleman.institutionprofile')),
            ],
            options={
                'verbose_name': 'plan wdrożenia',
                'verbose_name_plural': 'plany wdrożeń',
                'ordering': ['-created_at'],
            },
        ),
    ]
